#!/bin/sh

for year in $(ls -1 $SCRATCHDIR/StopsCompressed/cache/analysis)
do
    for sel in $(ls -1 $SCRATCHDIR/StopsCompressed/cache/analysis/$year)
    do
        for sample in $(ls -1 $SCRATCHDIR/StopsCompressed/cache/analysis/$year/$sel)
        do
	    nr=$(ls -1 $SCRATCHDIR/StopsCompressed/cache/analysis/$year/$sel/$sample | wc -l)
            printf "%-40s - %-12s - %-8s - %d\n" $sel $year $sample $nr
        done
    done
done
