python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleMuon_Run2017B_UL #SPLIT11
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleMuon_Run2017C_UL #SPLIT21
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleMuon_Run2017D_UL #SPLIT5 
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleMuon_Run2017E_UL #SPLIT26
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleMuon_Run2017F_UL #SPLIT70
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleElectron_Run2017B_UL #SPLIT5
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleElectron_Run2017C_UL #SPLIT10
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleElectron_Run2017D_UL #SPLIT5 
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleElectron_Run2017E_UL #SPLIT10
python nanoPostProcessing.py  --skim MetLepEnergy --year UL2017  --processingEra compstops_UL17v9_nano_v6 --triggerSelection  --sample SingleElectron_Run2017F_UL #SPLIT10
