#!/usr/bin/env python

from __future__ import print_function

import re
import os

SAMPLES_FILES = {
    'DATA2016' : 'Run2016_private_ULnanoAODv9',
    'MC2016' : 'UL16v9_private',
    'DATA2017' : 'Run2017_private_ULnanoAODv9',
    'MC2017' : 'UL17v9_private',
}

for sample in sorted(SAMPLES_FILES.keys()):
    print(sample)
    fname = os.path.realpath("../../Samples/nanoAOD/python/%s.py" % SAMPLES_FILES[sample])
    if not os.path.exists(fname):
        print( 'File %s does not exists.' % fname)
        continue
    with open(fname, 'r') as inp:
        data = inp.read()

    for match in re.finditer('Sample.fromDirectory\(\"([^\"]+)\"\s*,\s*\"([^\"]+)\"', data, re.M):
        sample, path = match.groups()
        nr_files = 0
        for root, dirs, files in os.walk(path):
            nr_files += len(files)

        print('Sample %s: %d files' % (sample, nr_files))


    