#!/bin/sh

NFSPATH="/groups/hephy/cms/$USER/StopsCompressed/nanoTuples"
EOSPATH="/eos/vbc/experiments/cms/store/user/liko/StopsCompressed/nanoTuples"
for name in $(find "$NFSPATH" -type f -printf "%P\n")
do
    if [ ! -e "$EOSPATH/$name" ]
    then
        echo "Copying $name ..."
        xrdcp --nopbar --retry 3 "$NFSPATH/$name" "root://eos.grid.vbc.ac.at/$EOSPATH/$name"
    fi
done