#!/bin/bash

EOSPATH="/eos/vbc/experiments/cms/store/user/liko/StopsCompressed/nanoTuples"
SCRATCHPATH="/scratch-cbe/users/dietrich.liko/StopsCompressed/nanoTuples"
for name in $(find "$EOSPATH" -type f -printf "%P\n")
do
    if [ ! -e "$SCRATCHPATH/$name" ]
    then
        echo "Copying $name ..."
        destdir="$(dirname "$SCRATCHPATH/$name")"
        if [ ! -e "$destdir" ]
        then
            mkdir -p "$destdir"
        fi
        xrdcp --nopbar --retry 3 "root://eos.grid.vbc.ac.at/$EOSPATH/$name" "$SCRATCHPATH/$name"
    fi
done